### ISSUE TITLE
Improve error message when window.ethereum is not defined

### ISSUE THREAD

**Issue by atfornes** [bloxberg-org/peer-review-app#11]
When using a browser without Metamask or other wallets, the client crashes with the cryptic message `TypeError: window.ethereum is undefined`.

Suggestions to install a wallet or using compatible browsers would be appreciated.

**Comment by kuzdogan** [comment]
This should be resolved with a82f628d50a4fc93e8d3e23c7e5758655d1a8163 and efd55f87eeb1704dcec27281b4fd4b8dc607bcfc . Feel free to re-open the issue if not working.
