### ISSUE TITLE
Error: No user found

### ISSUE THREAD

**Issue by atfornes** [bloxberg-org/peer-review-app#17]
After following the installation instructions, we get a "No user found :( Please register or switch users" message.

 see commit a82f628 for a possible cause or hint.

**Comment by atfornes** [comment]
We got this error message because we failed to correctly do the truffle migration...

I don't know if closing the issue or keep it open to offer more clarifying error messages

**Comment by kuzdogan** [comment]
Great 👍 Let's keep it open and I'll add a better error message.
