### ISSUE TITLE
ORCid Integration for Login

### ISSUE THREAD

**Issue by atfornes** [bloxberg-org/peer-review-app#30]
orcid.org/ is an industry standard to identify academic authors.

Impementing a way to sign in with Orcid (Using their OAuth API) could facilitate adoption and enable identity verifications

**Comment by crossoveranx** [comment]
I recommend this be integrated on the register profile page after the web3 provider is injected into the page in order to populate more information from the user. The data shouldn't be stored on the blockchain but rather the DB

**Comment by atfornes** [comment]
I would consider allowing reviewers to record their Orcid on the blockchain, then we can have a Endorsement mechanism similar to reviews endorsement to support they own their claimed identity: Each service that see that the reviewer owns an Orcid can "endorse" this identity claim.

**Comment by crossoveranx** [comment]
Ideally, I would like to implement a DID system on bloxberg in a more general sense to cover this use case. This could be part of (social endorsement for an identity) but I think scientific identity is too complex of an addition to integrate directly in the peer review app. This would be an interesting BLIP to work on though.

**Comment by atfornes** [comment]
I agree, Identities are complex, I had a recent nuanced [discussion on twitter about this](https://twitter.com/tomdemeranville/status/1272508812373766146) with Peerage of Science and ORCID. As you said, probably a BLIP with a similar approach for endorsing identities as BLIP-3 has for endorsing peer reviews would work :)

**Comment by kuzdogan** [comment]
1e4f0ade8b597af5c091038c569fe2c1b9eefef8 partially implements this
