### ISSUE TITLE
Add a template config file 

### ISSUE THREAD

**Issue by kuzdogan** [bloxberg-org/peer-review-app#8]
Add a template config file for installation. Config files should be local and not be stored in the repo. Currently, a temple is missing though.

**Comment by atfornes** [comment]
This would be great!

Currently I am not able to run the app due to lack of directions on how to configure these config settings.

Concretelly:

1. How to initiate a working database
2. Configure the development blockchain network, as I am currently getting this error: `Error: ReviewStorage has not been deployed to detected network (network/artifact mismatch)`

**Comment by kuzdogan** [comment]
Added the config file for the database at `server/config_template.js` and for the blockchain server secret at `dev/scripts/secret-template.sh`.

I am using a shell script to kickstart my dev environment in a `tmux` session. After configuring correctly you can run 
```
$ bash ./dev/bloxberg-dev.sh
```
to start the frontend, backend, and the ganache blockchain. Assuming you have `tmux` and VSCode installed. 

You have to migrate contracts manually by
```
$ truffle migrate --network develop
```
or navigate to the `4: truffle` tab in `tmux` and run without the initial truffle argument. To navigate use `Ctrl+B` followed by the tab number. 

I'm not collaborating atm with anyone so I haven't documented things well yet but will look into that. Feel free to comment or open new issues. Also, close this one if this resolves the issue. Thanks for your contributions!

**Comment by atfornes** [comment]
I did some changes in README.md that should help a bit with the installation and configuration: https://github.com/bloxberg-org/peer-review-app/pull/12

I managed to see the app working!

**Comment by kuzdogan** [comment]
You can close this issue if you manage to run the app and the database @atfornes

**Comment by atfornes** [comment]
I am still having issues with the configuration.

I had to guess which eth adress to add to the database, and even when that works I get this error:
```
Error adding to the blockchain
TypeError: instance.addReview is not a function
```

**Comment by kuzdogan** [comment]
Error when adding was due to 5a830a10df6022fb5ed4fee980df31d2ed356e15 . The function was set to private. Fixed.
